# Generated by Django 5.0.7 on 2024-07-15 19:10

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Anticipo",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("centro_costo", models.CharField(max_length=50)),
                ("nit", models.CharField(max_length=20)),
                ("nombre", models.CharField(max_length=100)),
                ("producto_servicio", models.CharField(max_length=200)),
                ("cantidad", models.IntegerField()),
                ("vlr_unitario", models.DecimalField(decimal_places=2, max_digits=10)),
                ("subtotal", models.DecimalField(decimal_places=2, max_digits=10)),
                ("iva", models.DecimalField(decimal_places=2, max_digits=10)),
                ("retencion", models.DecimalField(decimal_places=2, max_digits=10)),
                ("total_pagar", models.DecimalField(decimal_places=2, max_digits=10)),
                ("observaciones", models.CharField(max_length=200)),
            ],
            options={
                "db_table": "anticipos",
                "ordering": ["-id"],
                "unique_together": {("centro_costo", "nit", "producto_servicio")},
            },
        ),
    ]
