# Generated by Django 5.0.7 on 2024-07-15 19:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('anticipos', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='anticipo',
            table='anticipos',
        ),
    ]
