# Generated by Django 5.0.7 on 2024-07-15 20:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('anticipos', '0002_alter_anticipo_table'),
    ]

    operations = [
        migrations.AddField(
            model_name='anticipo',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='anticipo',
            name='foto_producto',
            field=models.ImageField(blank=True, null=True, upload_to='fotos_empleados/'),
        ),
        migrations.AddField(
            model_name='anticipo',
            name='updated',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
