# Generated by Django 5.0.7 on 2024-07-15 22:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('anticipos', '0004_alter_anticipo_iva_alter_anticipo_retencion_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='anticipo',
            name='iva',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
        migrations.AlterField(
            model_name='anticipo',
            name='retencion',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
        migrations.AlterField(
            model_name='anticipo',
            name='subtotal',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
        migrations.AlterField(
            model_name='anticipo',
            name='total_pagar',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
        migrations.AlterField(
            model_name='anticipo',
            name='vlr_unitario',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
    ]
