# Generated by Django 5.0.7 on 2024-07-16 13:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('anticipos', '0005_alter_anticipo_iva_alter_anticipo_retencion_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='anticipo',
            name='foto_producto',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='anticipo',
            name='iva',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
    ]
